<?xml version="1.0" encoding="utf-8"?><Database Name="Kadr" Class="KadrDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ugtudb.ugtu.net;Initial Catalog=Kadr;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KadrConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="ShemaTabel.ApproverType" Member="ApproverType">
    <Type Name="ApproverType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApproverTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApproveNumber" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Association Name="ApproverType_Approver" Member="Approver" ThisKey="id" OtherKey="idApproverType" Type="Approver" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.EmployeeEvent" Member="EmployeeEvent">
    <Type Name="EmployeeEvent">
      <Column Name="idEventSuperType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idFactStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EventSuperType_EmployeeEvent" Member="EventSuperType" ThisKey="idEventSuperType" OtherKey="id" Type="EventSuperType" IsForeignKey="true" />
      <Association Name="FactStaff_EmployeeEvent" Member="FactStaff" ThisKey="idFactStaff" OtherKey="id" Type="FactStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.EventSuperType" Member="EventSuperType">
    <Type Name="EventSuperType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDayStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FirstEventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="EventSuperType_EmployeeEvent" Member="EmployeeEvent" ThisKey="id" OtherKey="idEventSuperType" Type="EmployeeEvent" Cardinality="One" />
      <Association Name="DayStatus_EventSuperType" Member="DayStatus" ThisKey="idDayStatus" OtherKey="id" Type="DayStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.Exception" Member="Exception">
    <Type Name="Exception">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExceptionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateException" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idDayStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KolHourMPS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="KolHourMNS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="KolHourGPS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="KolHourGNS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="idWorkShedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="WorkShedule_Exception" Member="WorkShedule" ThisKey="idWorkShedule" OtherKey="id" Type="WorkShedule" IsForeignKey="true" />
      <Association Name="DayStatus_Exception" Member="DayStatus" ThisKey="idDayStatus" OtherKey="id" Type="DayStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.TimeSheetApproval" Member="TimeSheetApproval">
    <Type Name="TimeSheetApproval">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idApprover" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTimeSheet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApprovalDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Approver_TimeSheetApproval" Member="Approver" ThisKey="idApprover" OtherKey="id" Type="Approver" IsForeignKey="true" />
      <Association Name="TimeSheet_TimeSheetApproval" Member="TimeSheet" ThisKey="idTimeSheet" OtherKey="id" Type="TimeSheet" IsForeignKey="true" />
      <Association Name="TimeSheetView_TimeSheetApproval" Member="TimeSheetView" ThisKey="idTimeSheet" OtherKey="id" Type="TimeSheetView" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.WorkShedule" Member="WorkShedule">
    <Type Name="WorkShedule">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameShedule" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="WorkShedule_Exception" Member="Exception" ThisKey="id" OtherKey="idWorkShedule" Type="Exception" />
      <Association Name="WorkShedule_PlanStaff" Member="PlanStaff" ThisKey="id" OtherKey="IdWorkShedule" Type="PlanStaff" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Post">
    <Type Name="Post">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PostShortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ManagerBit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idGlobalPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPKCategory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Post_PlanStaff" Member="PlanStaff" ThisKey="id" OtherKey="idPost" Type="PlanStaff" />
      <Association Name="Category_Post" Member="Category" ThisKey="idCategory" OtherKey="id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.ApperoveDepartment" Member="ApperoveDepartment">
    <Type Name="ApperoveDepartment">
      <Column Name="idApprover" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idDepartment" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Approver_ApperoveDepartment" Member="Approver" ThisKey="idApprover" OtherKey="id" Type="Approver" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.Approver" Member="Approver">
    <Type Name="Approver">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idApproverType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDepartment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Approver_TimeSheetApproval" Member="TimeSheetApproval" ThisKey="id" OtherKey="idApprover" Type="TimeSheetApproval" />
      <Association Name="Approver_ApperoveDepartment" Member="ApperoveDepartment" ThisKey="id" OtherKey="idApprover" Type="ApperoveDepartment" />
      <Association Name="Approver_TimeSheet" Member="TimeSheet" ThisKey="id" OtherKey="idCreater" Type="TimeSheet" />
      <Association Name="Approver_TimeSheetView" Member="TimeSheetView" ThisKey="id" OtherKey="idCreater" Type="TimeSheetView" />
      <Association Name="ApproverType_Approver" Member="ApproverType" ThisKey="idApproverType" OtherKey="id" Type="ApproverType" IsForeignKey="true" />
      <Association Name="Employee_Approver" Member="Employee" ThisKey="idEmployee" OtherKey="id" Type="Employee" IsForeignKey="true" />
      <Association Name="Dep_Approver" Member="Dep" ThisKey="idDepartment" OtherKey="id" Type="Dep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Category">
    <Type Name="Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategorySmallName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPPS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Category_Post" Member="Post" ThisKey="id" OtherKey="idCategory" Type="Post" />
    </Type>
  </Table>
  <Table Name="dbo.FactStaffCurrent" Member="FactStaffCurrent">
    <Type Name="FactStaffCurrent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffCount" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="idPlanStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idBeginPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTypeWork" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsReplacement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idFactStaffHistory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateEndR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateBeginR" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idLaborContaraktMain" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idLaborContraktHistory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FactStaffCurrent_FactStaff" Member="FactStaff" ThisKey="id" OtherKey="id" Type="FactStaff" Cardinality="One" />
      <Association Name="FactStaffCurrent_PlanStaff" Member="PlanStaff" ThisKey="idPlanStaff" OtherKey="id" Type="PlanStaff" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.OK_Otpuskvid" Member="OK_Otpuskvid">
    <Type Name="OK_Otpuskvid">
      <Column Name="idotpuskvid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="otpuskvidname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idDayStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OK_Otpuskvid_OK_Otpusk" Member="OK_Otpusks" ThisKey="idotpuskvid" OtherKey="idOtpuskVid" Type="OK_Otpusk" />
      <Association Name="DayStatus_OK_Otpuskvid" Member="DayStatus" ThisKey="idDayStatus" OtherKey="id" Type="DayStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itab_n" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Otch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BirthPlace" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SexBit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idGrazd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSemPol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeverKoeff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RayonKoeff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeSid" Type="System.Data.Linq.Binary" DbType="VarBinary(85)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EmployeeLogin" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="AllowBirthdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="paspser" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="paspnomer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="paspdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="paspkem" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="inn" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ssgps" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="medpolis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employee_Approver" Member="Approver" ThisKey="id" OtherKey="idEmployee" Type="Approver" />
      <Association Name="Employee_FactStaff" Member="FactStaff" ThisKey="id" OtherKey="idEmployee" Type="FactStaff" />
      <Association Name="Employee_OK_Inkapacity" Member="OK_Inkapacities" ThisKey="id" OtherKey="idEmployee" Type="OK_Inkapacity" />
      <Association Name="FactStaffWithHistory_Employee" Member="FactStaffWithHistory" ThisKey="id" OtherKey="idEmployee" Type="FactStaffWithHistory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FactStaff" Member="FactStaff">
    <Type Name="FactStaff">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPlanStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsReplacement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDShedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idlaborcontrakt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idreason" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFundingDepartment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTimeSheetSheduleType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FactStaff_EmployeeEvent" Member="EmployeeEvent" ThisKey="id" OtherKey="idFactStaff" Type="EmployeeEvent" />
      <Association Name="FactStaff_FactStaffHistory" Member="FactStaffHistory" ThisKey="id" OtherKey="idFactStaff" Type="FactStaffHistory" />
      <Association Name="FactStaff_OK_Otpusk" Member="OK_Otpusks" ThisKey="id" OtherKey="idFactStaff" Type="OK_Otpusk" />
      <Association Name="Employee_FactStaff" Member="Employee" ThisKey="idEmployee" OtherKey="id" Type="Employee" IsForeignKey="true" />
      <Association Name="PlanStaff_FactStaff" Member="PlanStaff" ThisKey="idPlanStaff" OtherKey="id" Type="PlanStaff" IsForeignKey="true" />
      <Association Name="FactStaffCurrent_FactStaff" Member="FactStaffCurrent" ThisKey="id" OtherKey="id" Type="FactStaffCurrent" IsForeignKey="true" />
      <Association Name="FactStaffWithHistory_FactStaff" Member="FactStaffWithHistory" ThisKey="id" OtherKey="id" Type="FactStaffWithHistory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlanStaff" Member="PlanStaff">
    <Type Name="PlanStaff">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDepartment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdWorkShedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PlanStaff_FactStaff" Member="FactStaff" ThisKey="id" OtherKey="idPlanStaff" Type="FactStaff" />
      <Association Name="PlanStaff_Dep" Member="Dep1" ThisKey="id" OtherKey="idManagerPlanStaff" Type="Dep" />
      <Association Name="Post_PlanStaff" Member="Post" ThisKey="idPost" OtherKey="id" Type="Post" IsForeignKey="true" />
      <Association Name="WorkShedule_PlanStaff" Member="WorkShedule" ThisKey="IdWorkShedule" OtherKey="id" Type="WorkShedule" IsForeignKey="true" />
      <Association Name="FactStaffCurrent_PlanStaff" Member="FactStaffCurrent" ThisKey="id" OtherKey="idPlanStaff" Type="FactStaffCurrent" IsForeignKey="true" />
      <Association Name="FactStaffWithHistory_PlanStaff" Member="FactStaffWithHistory" ThisKey="id" OtherKey="idPlanStaff" Type="FactStaffWithHistory" IsForeignKey="true" />
      <Association Name="Dep_PlanStaff" Member="Dep" ThisKey="idDepartment" OtherKey="id" Type="Dep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FactStaffWithHistory" Member="FactStaffWithHistory">
    <Type Name="FactStaffWithHistory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffCount" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="HourCount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="HourSalary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="idPlanStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idBeginPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTypeWork" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsReplacement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="idFactStaffHistory" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDShedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSalaryKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idlaborcontrakt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idreason" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HourStaffCount" Type="System.Decimal" DbType="Decimal(6,4)" CanBeNull="true" />
      <Column Name="CalcStaffCount" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Association Name="FactStaffWithHistory_Employee" Member="Employee" ThisKey="idEmployee" OtherKey="id" Type="Employee" Cardinality="One" />
      <Association Name="FactStaffWithHistory_FactStaff" Member="FactStaff" ThisKey="id" OtherKey="id" Type="FactStaff" Cardinality="One" />
      <Association Name="FactStaffWithHistory_PlanStaff" Member="PlanStaff" ThisKey="idPlanStaff" OtherKey="id" Type="PlanStaff" Cardinality="One" />
      <Association Name="FactStaffWithHistory_FactStaffHistory" Member="FactStaffHistory" ThisKey="idFactStaffHistory" OtherKey="id" Type="FactStaffHistory" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.FactStaffHistory" Member="FactStaffHistory">
    <Type Name="FactStaffHistory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idFactStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idBeginPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StaffCount" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" CanBeNull="false" />
      <Column Name="idTypeWork" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idlaborcontrakt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HourCount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="HourSalary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="idSalaryKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HourStaffCount" Type="System.Decimal" DbType="Decimal(6,4)" CanBeNull="true" />
      <Column Name="CalcStaffCount" Type="System.Decimal" DbType="Decimal(6,4) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="FactStaffHistory_Event" Member="Events" ThisKey="id" OtherKey="idFactStaffHistory" Type="Event" />
      <Association Name="FactStaffHistory_TimeSheetRecord" Member="TimeSheetRecords" ThisKey="id" OtherKey="idFactStaffHistory" Type="TimeSheetRecord" />
      <Association Name="FactStaff_FactStaffHistory" Member="FactStaff" ThisKey="idFactStaff" OtherKey="id" Type="FactStaff" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="FactStaffWithHistory_FactStaffHistory" Member="FactStaffWithHistory" ThisKey="id" OtherKey="idFactStaffHistory" Type="FactStaffWithHistory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.DayStatus" Member="DayStatus">
    <Type Name="DayStatus">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DayStatusName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DayStatusFullName" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DayStatus_EventSuperType" Member="EventSuperType" ThisKey="id" OtherKey="idDayStatus" Type="EventSuperType" />
      <Association Name="DayStatus_Exception" Member="Exception" ThisKey="id" OtherKey="idDayStatus" Type="Exception" />
      <Association Name="DayStatus_OK_Otpuskvid" Member="OK_Otpuskvid" ThisKey="id" OtherKey="idDayStatus" Type="OK_Otpuskvid" />
      <Association Name="DayStatus_TimeSheetRecord" Member="TimeSheetRecords" ThisKey="id" OtherKey="idDayStatus" Type="TimeSheetRecord" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.TimeSheet" Member="TimeSheet">
    <Type Name="TimeSheet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDepartment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCreater" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateBeginPeriod" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateEndPeriod" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateComposition" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idWF" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ApproveStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFake" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TimeSheet_TimeSheetApproval" Member="TimeSheetApproval" ThisKey="id" OtherKey="idTimeSheet" Type="TimeSheetApproval" />
      <Association Name="TimeSheet_TimeSheetRecord" Member="TimeSheetRecords" ThisKey="id" OtherKey="idTimeSheet" Type="TimeSheetRecord" />
      <Association Name="Approver_TimeSheet" Member="Approver" ThisKey="idCreater" OtherKey="id" Type="Approver" IsForeignKey="true" />
      <Association Name="Dep_TimeSheet" Member="Dep" ThisKey="idDepartment" OtherKey="id" Type="Dep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dep" Member="Dep">
    <Type Name="Dep">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDepartmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KadrID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idManagerPlanStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeverKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RayonKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="idFundingCenter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasTimeSheet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Dep_Approver" Member="Approver" ThisKey="id" OtherKey="idDepartment" Type="Approver" />
      <Association Name="Dep_PlanStaff" Member="PlanStaff" ThisKey="id" OtherKey="idDepartment" Type="PlanStaff" />
      <Association Name="Dep_TimeSheet" Member="TimeSheet" ThisKey="id" OtherKey="idDepartment" Type="TimeSheet" />
      <Association Name="Dep_Department" Member="Department" ThisKey="id" OtherKey="id" Type="Department" Cardinality="One" />
      <Association Name="Dep_TimeSheetView" Member="TimeSheetView" ThisKey="id" OtherKey="idDepartment" Type="TimeSheetView" />
      <Association Name="PlanStaff_Dep" Member="PlanStaff1" ThisKey="idManagerPlanStaff" OtherKey="id" Type="PlanStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Department">
    <Type Name="Department">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentSmallName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idDepartmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idManagerDepartment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KadrID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idManagerPlanStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idBeginPrikaz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEndPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeverKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RayonKoeff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="idFundingCenter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasTimeSheet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Dep_Department" Member="Dep" ThisKey="id" OtherKey="id" Type="Dep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.TimeSheetView" Member="TimeSheetView">
    <Type Name="TimeSheetView">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDepartment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCreater" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateBeginPeriod" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateEndPeriod" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateComposition" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsFake" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeCount" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="ApproveStep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TimeSheetView_TimeSheetApproval" Member="TimeSheetApproval" ThisKey="id" OtherKey="idTimeSheet" Type="TimeSheetApproval" />
      <Association Name="Dep_TimeSheetView" Member="Dep" ThisKey="idDepartment" OtherKey="id" Type="Dep" IsForeignKey="true" />
      <Association Name="Approver_TimeSheetView" Member="Approver" ThisKey="idCreater" OtherKey="id" Type="Approver" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OK_Inkapacity" Member="OK_Inkapacities">
    <Type Name="OK_Inkapacity">
      <Column Name="idInkapacity" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NInkapacity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_OK_Inkapacity" Member="Employee" ThisKey="idEmployee" OtherKey="id" Type="Employee" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_BusinessTrip" Member="Event_BusinessTrips">
    <Type Name="Event_BusinessTrip">
      <Column Name="idEvent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idBusinessTrip" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_Event_BusinessTrip" Member="Event" ThisKey="idEvent" OtherKey="id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idMainEvent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPrikazEnd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idFactStaffHistory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEventKind" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEventType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idContract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Event_Event_BusinessTrip" Member="Event_BusinessTrip" ThisKey="id" OtherKey="idEvent" Type="Event_BusinessTrip" Cardinality="One" />
      <Association Name="Event_Event" Member="Events" ThisKey="id" OtherKey="idMainEvent" Type="Event" />
      <Association Name="Event_OK_Otpusk" Member="OK_Otpusks" ThisKey="id" OtherKey="idFactStaffPrikaz" Type="OK_Otpusk" />
      <Association Name="FactStaffHistory_Event" Member="FactStaffHistory" ThisKey="idFactStaffHistory" OtherKey="id" Type="FactStaffHistory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Event_Event" Member="Event1" ThisKey="idMainEvent" OtherKey="id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShemaTabel.TimeSheetRecord" Member="TimeSheetRecords">
    <Type Name="TimeSheetRecord">
      <Column Name="RecordDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JobTimeCount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="idTimeSheet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDayStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsChecked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="idFactStaffHistory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTimeSheetRecord" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NightTimeCount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="FactStaffHistory_TimeSheetRecord" Member="FactStaffHistory" ThisKey="idFactStaffHistory" OtherKey="id" Type="FactStaffHistory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TimeSheet_TimeSheetRecord" Member="TimeSheet" ThisKey="idTimeSheet" OtherKey="id" Type="TimeSheet" IsForeignKey="true" />
      <Association Name="DayStatus_TimeSheetRecord" Member="DayStatus" ThisKey="idDayStatus" OtherKey="id" Type="DayStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OK_Otpusk" Member="OK_Otpusks">
    <Type Name="OK_Otpusk">
      <Column Name="idOtpusk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idFactStaff" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idOtpuskVid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idOtpuskPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CountDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountDayFND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OtpPeriodWork" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="idFactStaffPrikaz" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSocialFareTransit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FactStaff_OK_Otpusk" Member="FactStaff" ThisKey="idFactStaff" OtherKey="id" Type="FactStaff" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Event_OK_Otpusk" Member="Event" ThisKey="idFactStaffPrikaz" OtherKey="id" Type="Event" IsForeignKey="true" />
      <Association Name="OK_Otpuskvid_OK_Otpusk" Member="OK_Otpuskvid" ThisKey="idOtpuskVid" OtherKey="idotpuskvid" Type="OK_Otpuskvid" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="ShemaTabel.CreateTimeSheet" Method="CreateTimeSheet">
    <Parameter Name="idDepartment" Type="System.Int32" DbType="Int" />
    <Parameter Name="idCrater" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateBeginPeriod" Parameter="dateBeginPeriod" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DateEndPeriod" Parameter="dateEndPeriod" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DateComposition" Parameter="dateComposition" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdTimeSheet" Parameter="idTimeSheet" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.add_EmplLogin" Method="add_EmplLogin">
    <Parameter Name="itab_n" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="EmployeeSid" Parameter="employeeSid" Type="System.Data.Linq.Binary" DbType="VarBinary(85)" />
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FIOToDat" Method="FIOToDat" IsComposable="true">
    <Parameter Name="FIO" Parameter="fIO" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="kind" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="ShemaTabel.TimeSheetRecordInsert" Method="TimeSheetRecordInsert">
    <Parameter Name="ValidXMLInput" Parameter="validXMLInput" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Return Type="System.Int32" />
  </Function>
</Database>