//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApperoveDepartment
    {
        public int idApprover { get; set; }
        public int idDepartment { get; set; }
    
        public virtual Approver Approver { get; set; }
    }
}
