//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproverType
    {
        public ApproverType()
        {
            this.Approver = new HashSet<Approver>();
        }
    
        public int id { get; set; }
        public string ApproverTypeName { get; set; }
        public Nullable<int> ApproveNumber { get; set; }
    
        public virtual ICollection<Approver> Approver { get; set; }
    }
}
