//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public Approver()
        {
            this.ApperoveDepartment = new HashSet<ApperoveDepartment>();
            this.TimeSheetApproval = new HashSet<TimeSheetApproval>();
            this.TimeSheet = new HashSet<TimeSheet>();
        }
    
        public int id { get; set; }
        public System.DateTime DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int idApproverType { get; set; }
        public int idDepartment { get; set; }
        public int idEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ApperoveDepartment> ApperoveDepartment { get; set; }
        public virtual ApproverType ApproverType { get; set; }
        public virtual ICollection<TimeSheetApproval> TimeSheetApproval { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
    }
}
