//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Post = new HashSet<Post>();
            this.Post1 = new HashSet<Post>();
        }
    
        public int id { get; set; }
        public string CategoryName { get; set; }
        public string CategorySmallName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsPPS { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<Post> Post1 { get; set; }
    }
}
