//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayStatus
    {
        public DayStatus()
        {
            this.EventSuperType = new HashSet<EventSuperType>();
            this.Exception = new HashSet<Exception>();
            this.TimeSheetRecord = new HashSet<TimeSheetRecord>();
        }
    
        public int id { get; set; }
        public string DayStatusName { get; set; }
        public string DayStatusFullName { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual ICollection<EventSuperType> EventSuperType { get; set; }
        public virtual ICollection<Exception> Exception { get; set; }
        public virtual ICollection<TimeSheetRecord> TimeSheetRecord { get; set; }
    }
}
