//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public int id { get; set; }
        public string ExceptionName { get; set; }
        public System.DateTime DateException { get; set; }
        public int idDayStatus { get; set; }
        public int idPrikaz { get; set; }
        public float KolHourMPS { get; set; }
        public float KolHourMNS { get; set; }
        public float KolHourGPS { get; set; }
        public float KolHourGNS { get; set; }
        public int idWorkShedule { get; set; }
    
        public virtual DayStatus DayStatus { get; set; }
        public virtual WorkShedule WorkShedule { get; set; }
    }
}
