//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostType
    {
        public PostType()
        {
            this.Post = new HashSet<Post>();
        }
    
        public int id { get; set; }
        public string PostTypeName { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
    }
}
