//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeatRate
    {
        public RepeatRate()
        {
            this.WorkSheduleEvent = new HashSet<WorkSheduleEvent>();
        }
    
        public int id { get; set; }
        public int DaysRepeat { get; set; }
    
        public virtual ICollection<WorkSheduleEvent> WorkSheduleEvent { get; set; }
    }
}
