//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetView
    {
        public int id { get; set; }
        public int idDepartment { get; set; }
        public int idCreater { get; set; }
        public System.DateTime DateBeginPeriod { get; set; }
        public System.DateTime DateEndPeriod { get; set; }
        public System.DateTime DateComposition { get; set; }
        public bool IsFake { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public int ApproveStep { get; set; }
    }
}
