//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetRecord
    {
        public System.DateTime RecordDate { get; set; }
        public double JobTimeCount { get; set; }
        public int idTimeSheet { get; set; }
        public int idDayStatus { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public int idFactStaffHistory { get; set; }
        public System.Guid IdTimeSheetRecord { get; set; }
    
        public virtual DayStatus DayStatus { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
