//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetApproval
    {
        public int id { get; set; }
        public int idApprover { get; set; }
        public int idTimeSheet { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public bool Result { get; set; }
        public string Comment { get; set; }
    
        public virtual Approver Approver { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
