//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShedule
    {
        public WorkShedule()
        {
            this.Exception = new HashSet<Exception>();
            this.WorkSheduleEvent = new HashSet<WorkSheduleEvent>();
        }
    
        public int id { get; set; }
        public string NameShedule { get; set; }
    
        public virtual ICollection<Exception> Exception { get; set; }
        public virtual ICollection<WorkSheduleEvent> WorkSheduleEvent { get; set; }
    }
}
